services:
  - type: web
    name: churn-predictor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    repo: https://github.com/your-username/your-repo-name
    branch: main
    region: oregon
    plan: free
